server:
  port: 8082

swagger:
  title: Pong API
  description: Pong API that respond with a Pong to a Ping
  include: /api/.*

pong:
  rest: true
  servicebus: true

spring:
  application:
    name: pong
  cloud:
    azure:
      credential-file-path: classpath:authentication.json
      resource-group: tsivb-srv
      region: Central US
      eventhub:
        namespace: tsivb-eventhub
        checkpoint-storage-account: tsivbeventhubstorage
      servicebus:
        queue:
          enabled: false
        topic:
          enabled: false
      telemetry:
        enabled: false
      redis:
        enabled: false
    stream:
      bindings:
        ping:
          destination: ping
          group: $Default
        pong:
          destination: pong
          group: $Default

feign:
  hystrix:
    enabled: true

eureka:
# injected by vault or pipeline
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

azure:
# injected by vault or pipeline
#  servicebus:
#    connection: none