server:
  port: 8082

swagger:
  title: Pong API
  description: Pong API that respond with a Pong to a Ping
  include: /api/.*

pong:
  rest: true
  servicebus: true

spring:
  application:
    name: pong

feign:
  hystrix:
    enabled: true

eureka:
# injected by vault or pipeline
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

azure:
# injected by vault or pipeline
#  servicebus:
#    connection: none